Repository JakeM93/caravan, pull requests merged in 2021-08, with the labels that each got.

#83 Test seeds
  db/seeds.rb
Labels: PR

#84 Skip Authentication for /cars and /cars/id
  app/controllers/cars_controller.rb
  app/views/cars/show.html.erb
Labels: PR

#88 a lot of front end changes, some links added
  app/assets/images/.keep
  app/assets/images/car-home.png
  app/assets/images/final-icon.png
  app/assets/images/final-logo.png
  app/assets/images/logo-blue.png
  app/assets/images/logo.png
  app/assets/stylesheets/components/_avatar.scss
  app/assets/stylesheets/components/_button.scss
  app/assets/stylesheets/components/_card.scss
  app/assets/stylesheets/components/_footer.scss
  app/assets/stylesheets/components/_index.scss
  app/assets/stylesheets/components/_navbar.scss
  app/assets/stylesheets/config/_colors.scss
  app/assets/stylesheets/config/_fonts.scss
  app/views/bookings/my_bookings.html.erb
  app/views/cars/index.html.erb
  app/views/cars/my_cars.html.erb
  app/views/cars/show.html.erb
  app/views/layouts/application.html.erb
  app/views/pages/home.html.erb
  app/views/shared/_navbar.html.erb
Labels: PR

#87 Car photo upload
  .gitignore
  Gemfile
  Gemfile.lock
  app/controllers/cars_controller.rb
  app/models/car.rb
  app/views/cars/new.html.erb
  app/views/cars/show.html.erb
  config/environments/development.rb
  config/storage.yml
  db/migrate/20210804195248_create_active_storage_tables.active_storage.rb
  db/schema.rb
Labels: PR

#90 Redirect
  app/controllers/bookings_controller.rb
Labels: PR

#92 My_bookings title
  app/views/bookings/my_bookings.html.erb
Labels: PR

#95 Style updates
  Gemfile
  Gemfile.lock
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/components/_button.scss
  app/assets/stylesheets/components/_card.scss
  app/assets/stylesheets/components/_content.scss
  app/assets/stylesheets/components/_form.scss
  app/assets/stylesheets/components/_index.scss
  app/assets/stylesheets/components/_navbar.scss
  app/assets/stylesheets/components/_rating.scss
  app/assets/stylesheets/config/_colors.scss
  app/controllers/cars_controller.rb
  app/views/bookings/my_bookings.html.erb
  app/views/cars/index.html.erb
  app/views/cars/my_cars.html.erb
  app/views/cars/show.html.erb
  app/views/layouts/application.html.erb
  config/initializers/geocoder.rb
  db/migrate/20210806175313_add_coordinates_to_cars.rb
  db/migrate/20210806175742_add_addressdetail_to_cars.rb
  db/schema.rb
  db/seeds.rb
Labels: PR, Improvment

#102 Animation-homepage
  app/views/layouts/application.html.erb
  app/views/pages/home.html.erb
  package.json
  yarn.lock
Labels: PR

#104 added search function
  app/controllers/cars_controller.rb
  app/views/bookings/new.html.erb
  app/views/cars/index.html.erb
  app/views/pages/home.html.erb
Labels: PR

#105 Fix booking form
  app/assets/stylesheets/components/_form.scss
  app/views/bookings/new.html.erb
Labels: PR

#107 I absolutely hate css and anything else that has to do with front end
  app/views/cars/new.html.erb
Labels: Front-End

#109 Edit pg not as new
  app/views/cars/_form.html.erb
  app/views/cars/edit.html.erb
  app/views/cars/new.html.erb
Labels: PR

#110 changed search form to be inline
  app/assets/stylesheets/components/_button.scss
  app/assets/stylesheets/components/_card.scss
  app/assets/stylesheets/components/_content.scss
  app/assets/stylesheets/config/_colors.scss
  app/assets/stylesheets/pages/_home.scss
  app/views/bookings/new.html.erb
  app/views/cars/index.html.erb
  app/views/cars/show.html.erb
  app/views/pages/home.html.erb
  db/seeds.rb
Labels: PR

#112 Cars#show map
  app/assets/stylesheets/components/_content.scss
  app/controllers/cars_controller.rb
  app/javascript/packs/application.js
  app/javascript/plugins/init_mapbox.js
  app/models/car.rb
  app/views/cars/_form.html.erb
  app/views/cars/new.html.erb
  app/views/cars/show.html.erb
  app/views/layouts/application.html.erb
  ave!
  config/initializers/geocoder.rb
  db/migrate/20210807152010_add_county_to_cars.rb
  db/schema.rb
Labels: PR

#122 Cars#show default img
  app/views/cars/index.html.erb
  app/views/cars/my_cars.html.erb
  app/views/cars/show.html.erb
Labels: PR

#124 Added some local Car Assets for Test Users, Also edited the Images to…
  app/assets/images/Vauxhall-Corsa.jpg
  app/assets/images/Vauxhall-Corsa.jpg:Zone.Identifier
  app/assets/images/audi-q2.jpg
  app/assets/images/audi-q2.jpg:Zone.Identifier
  app/assets/images/bmw-m2.jpg
  app/assets/images/bmw-m2.jpg:Zone.Identifier
  app/assets/images/ford-mustang.jpg
  app/assets/images/ford-mustang.jpg:Zone.Identifier
  app/assets/images/ford-raptor.jpg
  app/assets/images/ford-raptor.jpg:Zone.Identifier
  app/assets/images/honda-civic.jpg
  app/assets/images/honda-civic.jpg:Zone.Identifier
  app/assets/images/lamborghini-aventador.jpg
  app/assets/images/lamborghini-aventador.jpg:Zone.Identifier
  app/assets/images/rangerover-sport.jpg
  app/assets/images/rangerover-sport.jpg:Zone.Identifier
  app/assets/images/smart-forfour.jpg
  app/assets/images/smart-forfour.jpg:Zone.Identifier
  app/assets/images/tesla-s.jpg
  app/assets/images/tesla-s.jpg:Zone.Identifier
  app/assets/images/toyota-aygo.jpg
  app/assets/images/toyota-aygo.jpg:Zone.Identifier
  app/assets/images/vauxhall-insignia.jpg
  app/assets/images/vauxhall-insignia.jpg:Zone.Identifier
  app/assets/images/vauxhall-moka.jpg
  app/assets/images/vauxhall-moka.jpg:Zone.Identifier
  app/assets/images/vauxhall-viva.jpg
  app/assets/images/vauxhall-viva.jpg:Zone.Identifier
  app/assets/images/volkswagen-golf.jpg
  app/assets/images/volkswagen-golf.jpg:Zone.Identifier
  app/views/bookings/my_bookings.html.erb
  app/views/cars/index.html.erb
  app/views/cars/my_cars.html.erb
  app/views/cars/show.html.erb
  db/seeds.rb
Labels: PR
