Repository JakeM93/caravan, pull requests merged in 2021-07, with the labels that each got.

#47 Cars#index
  app/controllers/cars_controller.rb
  app/views/cars/index.html.erb
  test/controllers/cars_controller_test.rb
Labels: PR

#55 Cars#new & cars#create
  app/controllers/cars_controller.rb
  app/views/cars/new.html.erb
Labels: PR

#59 edited cars new page
  app/controllers/bookings_controller.rb
  app/views/bookings/new.html.erb
  app/views/cars/index.html.erb
  app/views/cars/new.html.erb
Labels: PR

#61 Added homepage and footer
  app/assets/images/car.svg
  app/assets/images/driver.svg
  app/assets/images/order.svg
  app/assets/stylesheets/components/_button.scss
  app/assets/stylesheets/components/_footer.scss
  app/assets/stylesheets/components/_index.scss
  app/assets/stylesheets/pages/_home.scss
  app/views/layouts/application.html.erb
  app/views/pages/home.html.erb
  app/views/shared/_footer.html.erb
Labels: Front-End, PR

#62 removed dropdown from booking form
  app/views/bookings/new.html.erb
Labels: Front-End, PR

#60 Edit delete car if owner
  app/controllers/cars_controller.rb
  app/views/cars/edit.html.erb
  app/views/cars/show.html.erb
Labels: Front-End, Security
